# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bizfindr-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - FLASK_APP=app
      - FLASK_ENV=${FLASK_ENV:-development}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=bizfindr
      - REDIS_URL=redis://redis:6379/0
      - REDIS_CACHE_TTL=300
      - API_BASE_URL=https://data.ct.gov/resource/n7gp-d28j.json
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=300
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONFAULTHANDLER=1
      - MONGO_URI=mongodb://mongo:27017/bizfindr  # For backward compatibility
      - REDIS_PASSWORD=redispass
      - REDIS_URL=redis://:redispass@redis:6379/0
      - CACHE_REDIS_URL=redis://:redispass@redis:6379/0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bizfindr-network
      
  redis:
    image: redis:7.2-alpine
    container_name: bizfindr-redis
    command: redis-server --requirepass redispass --save "" --appendonly no
    environment:
      - REDIS_PASSWORD=redispass
    networks:
      - bizfindr-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M

  mongo:
    image: mongo:6.0
    container_name: bizfindr-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bizfindr
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bizfindr-network

  mongo-express:
    image: mongo-express:latest
    container_name: bizfindr-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - bizfindr-network

networks:
  bizfindr-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  mongo-data:
  mongo-config:
  mongo-init:
  redis-data:
