# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'bizfindr-monitor'

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rule files
rule_files:
  - 'alert.rules'

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the Flask application metrics
  - job_name: 'bizfindr'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: web:5000  # The Flask app's address

  # Scrape MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:9216']  # MongoDB Exporter
    metrics_path: /metrics

  # Scrape Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  # Scrape Blackbox Exporter
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'http://web:5000'  # The Flask app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The Blackbox Exporter

# Remote write configuration (optional, for long-term storage)
remote_write:
  - url: 'http://thanos-receive:19291/api/v1/receive'  # Example for Thanos
    queue_config:
      max_samples_per_send: 1000
      capacity: 10000
      max_shards: 30

# Remote read configuration (optional)
remote_read:
  - url: 'http://thanos-query:10904/api/v1/read'  # Example for Thanos Query
    read_recent: true
